# Generated by Django 3.2 on 2022-03-16 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori_Dokumen',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('kd_dokumen', models.AutoField(primary_key=True, serialize=False)),
                ('nama_dokumen', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='file/')),
                ('kategori_dok', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dokumen.kategori_dokumen')),
            ],
        ),
    ]
