# Generated by Django 3.2.8 on 2021-12-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen',
            name='kd_dokumen',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
