# Generated by Django 3.2.8 on 2022-02-22 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0002_alter_dokumen_kd_dokumen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori_Dokumen',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='dokumen',
            name='kategori_dok',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dokumen.kategori_dokumen'),
        ),
    ]
