# Generated by Django 3.2.8 on 2021-11-29 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id_buku', models.IntegerField(primary_key=True, serialize=False)),
                ('jdl_buku', models.CharField(max_length=100)),
                ('harga', models.CharField(max_length=10)),
                ('stok', models.IntegerField()),
                ('cover', models.FileField(upload_to='file/cover')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('totalreview', models.IntegerField(default=1)),
                ('totalrating', models.IntegerField(default=5)),
                ('status', models.IntegerField(default=0)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pengarang',
            fields=[
                ('id_pengarang', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_pengarang', models.CharField(max_length=100)),
                ('deskripsi_pengarang', models.CharField(max_length=100)),
                ('foto', models.FileField(upload_to='file/foto')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_star', models.IntegerField()),
                ('review_text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.buku')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('kd_jurnal', models.IntegerField(primary_key=True, serialize=False)),
                ('jdl_jurnal', models.CharField(max_length=100)),
                ('pengarang', models.CharField(max_length=100)),
                ('terbitan', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('abstract', models.TextField()),
                ('refrensi', models.TextField()),
                ('keywords', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='file/')),
                ('id_kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.kategori')),
            ],
        ),
        migrations.AddField(
            model_name='buku',
            name='id_kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.kategori'),
        ),
        migrations.AddField(
            model_name='buku',
            name='id_pengarang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.pengarang'),
        ),
    ]
