# Generated by Django 3.2.8 on 2021-12-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='id_buku',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='journal',
            name='kd_jurnal',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='id_kategori',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pengarang',
            name='id_pengarang',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
