# Generated by Django 3.2.8 on 2021-12-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20211208_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori_Journal',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=50)),
            ],
        ),
    ]
