# Generated by Django 3.2.8 on 2021-12-13 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_kategori_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='kategorij',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.kategori_journal'),
        ),
    ]
