# Generated by Django 3.2.8 on 2021-12-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_rename_id_kategori_kategori_journal_id_kategorij'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='totalrating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buku',
            name='totalreview',
            field=models.IntegerField(default=0),
        ),
    ]
