# Generated by Django 3.2.8 on 2021-12-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20211229_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='buku',
            name='totalrating',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='buku',
            name='totalreview',
            field=models.IntegerField(default=1),
        ),
    ]
