# Generated by Django 3.2 on 2022-03-16 17:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('kd_transaksi', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=30)),
                ('nama_belakang', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telepon', models.CharField(max_length=16)),
                ('asal_institusi', models.CharField(max_length=150)),
                ('payable', models.IntegerField()),
                ('total_buku', models.IntegerField()),
                ('tgl_transaksi', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('update', models.DateTimeField(auto_now=True)),
                ('bayar', models.BooleanField(default=False)),
                ('token', models.TextField(default=False)),
                ('Akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-tgl_transaksi',),
            },
        ),
        migrations.CreateModel(
            name='Item_Pembelian',
            fields=[
                ('kd_item', models.AutoField(primary_key=True, serialize=False)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.buku')),
                ('pembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.pembelian')),
            ],
        ),
    ]
