# Generated by Django 3.2 on 2022-01-01 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('kd_transaksi', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telepon', models.CharField(max_length=16)),
                ('instansi', models.CharField(max_length=150)),
                ('metode_pembayaran', models.CharField(max_length=20)),
                ('nomor_akun', models.CharField(max_length=20)),
                ('payable', models.IntegerField()),
                ('total_buku', models.IntegerField()),
                ('tgl_transaksi', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('bayar', models.BooleanField(default=False)),
                ('Akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-tgl_transaksi',),
            },
        ),
        migrations.CreateModel(
            name='Item_Pembelian',
            fields=[
                ('kd_item', models.AutoField(primary_key=True, serialize=False)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.buku')),
                ('pembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.pembelian')),
            ],
        ),
    ]
