# Generated by Django 3.2 on 2022-02-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220222_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembelian',
            name='nama_belakang',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
